services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "1115:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: quizzes-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d quizzes-db" ]
      interval: 20s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: